### ISSUE TITLE
Plugin is not working as expected.

### ISSUE THREAD

**Issue by qgou** [valtlfelipe/TinyMCE-LocalAutoSave#14] opened 2016-08-22 16:13 UTC
It only saves one version when I initially loaded the editor and started typing. Then no more saving after that no matter what more typing I did and how long I have been waiting for.

I installed it manually and all configuration is default. I have not explicitly changed any settings.

I tested in all 3 major browsers: IE 10, Firefox and Chrome, same result.

**Comment by valtlfelipe** [comment] 2016-08-22 23:46
Hi @qgou !

Can you reproduce this on the demo http://valtlfelipe.github.io/TinyMCE-LocalAutoSave/?
Is there anything in the developer console?

**Comment by qgou** [comment] 2016-08-23 12:20
Hi, there,
 
When I tested your demo url, it works fine as expected. 
 
I am using your plugin into my Alfresco tinyMCE editor. I don't see any error in the console. I will play more today.
 
Thanks for your reply.
 
Date: Mon, 22 Aug 2016 16:46:04 -0700

**Comment by valtlfelipe** [comment] 2016-08-30 00:21
Hi @qgou!

Did you find something out? I did some tests on all major browsers, and haven't experienced any issue.

**Comment by qgou** [comment] 2016-08-30 02:25
It looks like it is an integration issue. Still working on it...
 
Thanks for the follow-up.
 
Date: Mon, 29 Aug 2016 17:21:49 -0700

**Comment by valtlfelipe** [comment] 2016-09-08 21:54
I will close this issue, since there was no update in a while. If you still need help, feel free to reopen it, or create a new issue! :)

**Closed by valtlfelipe** 2016-09-08 21:54 UTC

**Comment by qgou** [comment] 2016-09-08 23:18
Sure.


________________________________
